"""The run plan: the conductor's view of one run, resolved from the profile and the contracts.

Python resolves the data (which stages, in what order, how each is dispatched, which
contracts and reference files exist); the conductor reads the plan and carries it out. The
plan is generated into ``<workspace>/.claude/archivist/run-plan.yaml`` on every load.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Sequence

import yaml

from archivist.contracts import CONFIDENCE_FIELD, GAPS_FIELD, STRUCTURE_FIELD, TargetContracts
from archivist.profile import Profile, Roster, entry_stage

PLAN_REL = Path(".claude") / "archivist" / "run-plan.yaml"
_HEADER = "# Generated by `archivist prepare-workspace` on every run. Edit agents/profile.yaml\n# or contracts/target.yaml instead.\n"


def build_run_plan(
    profile: Profile,
    roster: Roster,
    contracts: TargetContracts,
    *,
    kinds: Sequence[str] | None = None,
) -> dict[str, Any]:
    stages = []
    for name in roster.stages:
        spec = profile.agents[name]
        stage: dict[str, Any] = {"agent": name}
        if spec.produces:
            stage["produces"] = True
        stage["dispatch"] = dict(spec.dispatch or {})
        stages.append(stage)
    plan: dict[str, Any] = {
        "target": contracts.slug,
        "pipeline": roster.pipeline,
        "entry_stage": entry_stage(profile, roster),
        "planner": profile.planner if roster.authoring else None,
        # ADR 0006: documents of an `extract` intake class go to this agent before planning.
        "extractor": profile.extractor if roster.extracting else None,
        "stages": stages,
        # ADR 0004: `kinds` narrows the gap fleet; "all" means every enabled, applicable kind.
        "scope": {"kinds": list(kinds) if kinds else "all"},
        "contracts": {kind: contracts.rel(kind) for kind in sorted(contracts.paths)},
        "reference": {
            name: {"path": ref.rel, "description": ref.description}
            for name, ref in sorted(contracts.references.items())
        },
        "fields": {"gaps": GAPS_FIELD, "confidence": CONFIDENCE_FIELD, "structure": STRUCTURE_FIELD},
        "enrichment_methods": {
            name: dict(spec) for name, spec in sorted(profile.enrichment_methods.items())
        },
        "bookkeeping": {
            "catalog": "update-catalog skill, once per group after the last stage",
            "publish": "knowledge-repo-git, open-pull-request, file-gap-issues skills, when the kickoff says to publish",
        },
    }
    return plan


class _PlanDumper(yaml.SafeDumper):
    """Multi-line strings as literal blocks, so the conductor reads prompts as written."""


def _str(dumper: yaml.SafeDumper, value: str) -> yaml.ScalarNode:
    style = "|" if "\n" in value else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", value, style=style)


_PlanDumper.add_representer(str, _str)


def write_run_plan(workspace: Path, plan: dict[str, Any]) -> Path:
    path = workspace / PLAN_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    text = yaml.dump(plan, Dumper=_PlanDumper, sort_keys=False, allow_unicode=True, width=100)
    path.write_text(_HEADER + text, encoding="utf-8")
    return path
